[53776] Android + shared code: updated the todays numbers page with new elements, correct color etc.
folkehelseinstituttet/Fhi.Smittestopp.App pull request #350
Opened 2021-02-16 15:26 UTC by Michael-Olesen

2021-02-16 15:39 UTC, Frederik-S-N-dk requested changes

2021-02-16 15:39 UTC, Frederik-S-N-dk commented on NDB.Covid19/NDB.Covid19.Droid/Resources/layout/activity_daily_numbers.xml
> +                    android:layout_marginVertical="21dp"
use default margins

2021-02-16 15:39 UTC, Frederik-S-N-dk commented on NDB.Covid19/NDB.Covid19.Droid/Resources/layout/activity_daily_numbers.xml
>                  android:layout_marginHorizontal="24dp"
use default margin - and if we don't have one, then create one

2021-02-16 15:39 UTC, Frederik-S-N-dk commented on NDB.Covid19/NDB.Covid19.Droid/Resources/layout/activity_daily_numbers.xml
>                              android:paddingHorizontal="8dp"
create default margin to be used

2021-02-16 15:39 UTC, Frederik-S-N-dk commented on NDB.Covid19/NDB.Covid19.Droid/Resources/layout/activity_daily_numbers.xml
>                              android:paddingTop="8dp"
create default margin to be used

2021-02-16 15:39 UTC, Frederik-S-N-dk commented on NDB.Covid19/NDB.Covid19.Droid/Resources/layout/activity_daily_numbers.xml
>                      android:paddingVertical="8dp"
create default margin to be used

2021-02-16 15:39 UTC, Frederik-S-N-dk commented on NDB.Covid19/NDB.Covid19/ViewModels/DailyNumbersViewModel.cs
> +        //For now I assume that FHI will provide vaccination numbers and that these will arrive at the same time as other FHI provided numbers
delete this comment

2021-02-16 15:40 UTC, Michael-Olesen commented
forgot to add screenshot
![todays numbers 1](https://user-images.githubusercontent.com/78792881/108085297-79178080-7075-11eb-8026-edff9981458f.jpg)
![todays bumbers 2](https://user-images.githubusercontent.com/78792881/108085327-80d72500-7075-11eb-82a1-4e48254de7c5.jpg)

2021-02-22 09:05 UTC, Frederik-S-N-dk requested changes

2021-02-22 09:05 UTC, Frederik-S-N-dk commented on NDB.Covid19/NDB.Covid19.Droid/Resources/layout/activity_daily_numbers.xml
> +                            android:layout_marginEnd="16dp"
I see that you are using this "...marginEND = 16 dp" a couple of places. Please create a defualt dimen for this

2021-02-22 09:47 UTC, Frederik-S-N-dk approved these changes

2021-02-22 10:57 UTC, merged