[50024] Unified layouts in settings and welcome pages
folkehelseinstituttet/Fhi.Smittestopp.App pull request #45
Opened 2020-11-25 14:13 UTC by jonasofrich

![IMG_0135](https://user-images.githubusercontent.com/19961953/100238678-c5e53280-2f30-11eb-8314-1c0a2a618199.PNG)
![IMG_0134](https://user-images.githubusercontent.com/19961953/100238683-c7aef600-2f30-11eb-862e-ab68075bee10.PNG)
![IMG_0133](https://user-images.githubusercontent.com/19961953/100238688-c8478c80-2f30-11eb-8677-8aa29c52db48.PNG)
![IMG_0132](https://user-images.githubusercontent.com/19961953/100238691-c8e02300-2f30-11eb-9c08-63db03780245.PNG)
![IMG_0131](https://user-images.githubusercontent.com/19961953/100238694-c978b980-2f30-11eb-85e3-c982377eb012.PNG)
![IMG_0130](https://user-images.githubusercontent.com/19961953/100238696-ca115000-2f30-11eb-80a7-ca83a8542d72.PNG)
![IMG_0129](https://user-images.githubusercontent.com/19961953/100238701-ca115000-2f30-11eb-8814-c34ea7ebce64.PNG)
![IMG_0128](https://user-images.githubusercontent.com/19961953/100238705-caa9e680-2f30-11eb-9b3e-6ee162e0466f.PNG)
![IMG_0127](https://user-images.githubusercontent.com/19961953/100238707-caa9e680-2f30-11eb-96f2-bec19c2f6772.PNG)

2020-11-25 14:26 UTC, Frederik-S-N-dk approved these changes

2020-11-25 14:34 UTC, nc-kano requested changes
Buttons in welcome screen should have the same margin on lhe left and right side as the text has

2020-11-26 11:39 UTC, jonasofrich commented
Updated margins on buttons
![IMG_0142](https://user-images.githubusercontent.com/19961953/100346585-60eb1480-2fe4-11eb-8afa-d834879e29a9.PNG)
![IMG_0141](https://user-images.githubusercontent.com/19961953/100346589-62b4d800-2fe4-11eb-97c7-be1778d7a68c.PNG)
![IMG_0140](https://user-images.githubusercontent.com/19961953/100346592-634d6e80-2fe4-11eb-8794-109ffe9a8b31.PNG)
![IMG_0139](https://user-images.githubusercontent.com/19961953/100346594-63e60500-2fe4-11eb-901e-dcf929192eba.PNG)

2020-11-26 11:46 UTC, nc-kano approved these changes

2020-11-26 11:48 UTC, merged