[48560] Disable consents functionality for release 1
folkehelseinstituttet/Fhi.Smittestopp.App pull request #7
Opened 2020-11-18 13:12 UTC by nc-kano

2020-11-18 14:55 UTC, fsnNC approved these changes

2020-11-19 06:49 UTC, matishadow requested changes
I'm not too familiar with the project yet so take this comment with a grain of salt. 


The logic you introduced with `Conf.IsReleaseOne` is pretty scattered across the project.
Have you considered putting it in one class so it's all in one place? 

Plus the code is duplicated in both `NavigationHelper` classes.

2020-11-19 06:49 UTC, matishadow commented on NDB.Covid19/NDB.Covid19.Droid/Utils/NavigationHelper.cs
> +            if ((Conf.IsReleaseOne &&
Inner parentheses are redundant.

2020-11-19 06:49 UTC, matishadow commented on NDB.Covid19/NDB.Covid19.iOS/Utils/NavigationHelper.cs
> +            if ((Conf.IsReleaseOne &&
Inner parentheses are redundant.

2020-11-19 08:55 UTC, nc-kano commented on NDB.Covid19/NDB.Covid19.iOS/Utils/NavigationHelper.cs
> +            if ((Conf.IsReleaseOne &&
done

2020-11-19 08:55 UTC, nc-kano commented on NDB.Covid19/NDB.Covid19.Droid/Utils/NavigationHelper.cs
> +            if ((Conf.IsReleaseOne &&
done

2020-11-19 08:56 UTC, nc-kano commented
@matishadow Moved all IsReleaseOne logic to ConsentsHelperClass

2020-11-19 11:51 UTC, matishadow approved these changes
Really good!

2020-11-19 11:51 UTC, merged