[Cherry-pick] [CR0352][R2.1][94106] Send local notification when …
folkehelseinstituttet/Fhi.Smittestopp.App pull request #72
Opened 2020-11-27 16:02 UTC by nc-kano

…permissions are off with unit tests

Related work items: #94106

2020-11-30 09:00 UTC, pavshr requested changes
Need some clarification

2020-11-30 09:04 UTC, nc-kano commented on NDB.Covid19/NDB.Covid19.Droid/Utils/LocalNotificationManager.cs
> +        public const int PermissionsNotificationId = 161;
we just need to add any number to identify the notification. it can be anything

2020-11-30 09:06 UTC, nc-kano commented on NDB.Covid19/NDB.Covid19/PersistedData/LocalPreferencesHelper.cs
> +            get => _preferences.Get(PreferencesKeys.LAST_PERMISSIONS_NOTIFICATION_DATE_TIME, DateTime.MinValue);
we have not observe any issues with it in danish app. at least not yet.

2020-11-30 09:13 UTC, pavshr commented on NDB.Covid19/NDB.Covid19.Droid/NDB.Covid19.Droid.csproj
> +    <PackageReference Include="Xamarin.GooglePlayServices.SafetyNet">
SafetyNet

2020-11-30 09:58 UTC, nc-kano commented on NDB.Covid19/NDB.Covid19.Droid/NDB.Covid19.Droid.csproj
> +    <PackageReference Include="Xamarin.GooglePlayServices.SafetyNet">
ok, i will remove it. but i think it will be for the next deploy.

2020-12-01 10:45 UTC, nc-kano commented on NDB.Covid19/NDB.Covid19.iOS/Permissions/IOSPermissionsHelper.cs
> +            return true;
actually it will create more confusion in PermissionUtils. In my opinion all kinds of negations make it harder to read later.

2020-12-01 10:53 UTC, nc-kano commented on NDB.Covid19/NDB.Covid19.Droid/NDB.Covid19.Droid.csproj
> +    <PackageReference Include="Xamarin.GooglePlayServices.SafetyNet">
done

2020-12-02 11:29 UTC, pavshr approved these changes

2020-12-02 11:46 UTC, merged