[50447] Adjusted line break settings on headings in burger menu
folkehelseinstituttet/Fhi.Smittestopp.App pull request #96
Opened 2020-12-02 09:09 UTC by jonasofrich

2020-12-02 09:43 UTC, nc-kano approved these changes

2020-12-02 09:44 UTC, TMHolen95 commented
Still seeing issues on settings page 2,3 & 4. Entire title is not showing on page 2 and 3, while on page 3 the TextView below the title is overflowing to the right.

2020-12-02 09:46 UTC, TMHolen95 requested changes
Titles are still not working properly on iPhone SE 1 Gen

2020-12-04 07:28 UTC, nc-kano commented
@jonasofrich please resolve conflicts

2020-12-11 11:08 UTC, closed without merging